


export const raw_person_list = [
    {
      "emp_id": 0,
      "person_id": 31058338799,
      "first_name": "Jan",
      "last_name": "Andersen",
      "title": "Plattformsjef",
      "skift": 0,
      "Beredskapslag_1": 1,
      "Rolle_lag_1": 7,
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 1,
      "person_id": "01029838042",
      "first_name": "Ole",
      "last_name": "Berg",
      "title": "Driftsleder",
      "skift": 0,
      "Beredskapslag_1": 1,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 2,
      "person_id": 16045735412,
      "first_name": "Marianne",
      "last_name": "Andreassen",
      "title": "Vedlikeholdsleder",
      "skift": 0,
      "Beredskapslag_1": 1,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 3,
      "person_id": 28069620746,
      "first_name": "Hans",
      "last_name": "Bakken",
      "title": "Sikkerhetsleder",
      "skift": 0,
      "Beredskapslag_1": 1,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 4,
      "person_id": "02115439513",
      "first_name": "Ellen",
      "last_name": "Amundsen",
      "title": "Fagansvarlig prosess 1",
      "skift": 0,
      "Beredskapslag_1": 11,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 5,
      "person_id": "06107948013",
      "first_name": "Berit",
      "last_name": "Bakke",
      "title": "Fagansvarlig prosess 2",
      "skift": 0,
      "Beredskapslag_1": 8,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 6,
      "person_id": 22055402853,
      "first_name": "Terje",
      "last_name": "Berge",
      "title": "Sykepleier",
      "skift": 0,
      "Beredskapslag_1": 10,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 7,
      "person_id": 29055018233,
      "first_name": "Eva",
      "last_name": "Andresen",
      "title": "Catering 1",
      "skift": 0,
      "Beredskapslag_1": 6,
      "Rolle_lag_1": "",
      "Beredskapslag_2": 12,
      "Beredskapslag_3": 3
    },
    {
      "emp_id": 8,
      "person_id": 30117414945,
      "first_name": "Thomas",
      "last_name": "Christensen",
      "title": "Catering 2",
      "skift": 0,
      "Beredskapslag_1": 6,
      "Rolle_lag_1": 5,
      "Beredskapslag_2": 12,
      "Beredskapslag_3": 3
    },
    {
      "emp_id": 9,
      "person_id": 24016732326,
      "first_name": "Maria",
      "last_name": "Aas",
      "title": "Fagansvalig elektro",
      "skift": 0,
      "Beredskapslag_1": 4,
      "Rolle_lag_1": "",
      "Beredskapslag_2": 12,
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 10,
      "person_id": 10058513909,
      "first_name": "Nils",
      "last_name": "Berntsen",
      "title": "Stuert",
      "skift": 0,
      "Beredskapslag_1": 12,
      "Rolle_lag_1": "",
      "Beredskapslag_2": 6,
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 11,
      "person_id": "05075641240",
      "first_name": "Marie",
      "last_name": "Danielsen",
      "title": "Fagansvarlig mekanisk",
      "skift": 0,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": 9,
      "Beredskapslag_2": 7,
      "Beredskapslag_3": 3
    },
    {
      "emp_id": 12,
      "person_id": 10106849329,
      "first_name": "Lars",
      "last_name": "Arnesen",
      "title": "Elektriker",
      "skift": 0,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 13,
      "person_id": 17056349057,
      "first_name": "Tor",
      "last_name": "Antonsen",
      "title": "Prosessoperatør 1",
      "skift": 0,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 14,
      "person_id": 15058626691,
      "first_name": "Fredrik",
      "last_name": "Birkeland",
      "title": "Prosessoperatør 2",
      "skift": 0,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 15,
      "person_id": 19059349948,
      "first_name": "Liv",
      "last_name": "Aasen",
      "title": "Prosessoperatør 3",
      "skift": 0,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 16,
      "person_id": "04056400716",
      "first_name": "Silje",
      "last_name": "Bøe",
      "title": "Intrumenttekniker",
      "skift": 0,
      "Beredskapslag_1": 4,
      "Rolle_lag_1": "",
      "Beredskapslag_2": 12,
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 17,
      "person_id": 27066905050,
      "first_name": "Kristin",
      "last_name": "Aune",
      "title": "Mekaniker",
      "skift": 0,
      "Beredskapslag_1": 4,
      "Rolle_lag_1": 13,
      "Beredskapslag_2": 12,
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 18,
      "person_id": 20079339904,
      "first_name": "Solveig",
      "last_name": "Abrahamsen",
      "title": "Plattformsjef",
      "skift": 1,
      "Beredskapslag_1": 1,
      "Rolle_lag_1": 7,
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 19,
      "person_id": 20048402284,
      "first_name": "Gerd",
      "last_name": "Brekke",
      "title": "Driftsleder",
      "skift": 1,
      "Beredskapslag_1": 1,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 20,
      "person_id": 23098319190,
      "first_name": "Bjørg",
      "last_name": "Christiansen",
      "title": "Vedlikeholdsleder",
      "skift": 1,
      "Beredskapslag_1": 1,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 21,
      "person_id": 18068347455,
      "first_name": "Steinar",
      "last_name": "Bjerke",
      "title": "Sikkerhetsleder",
      "skift": 1,
      "Beredskapslag_1": 1,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 22,
      "person_id": 11114820034,
      "first_name": "Jon",
      "last_name": "Bråthen",
      "title": "Fagansvarlig prosess 1",
      "skift": 1,
      "Beredskapslag_1": 11,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 23,
      "person_id": 14088408080,
      "first_name": "Olav",
      "last_name": "Dahle",
      "title": "Fagansvarlig prosess 2",
      "skift": 1,
      "Beredskapslag_1": 8,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 24,
      "person_id": "03079032343",
      "first_name": "Kåre",
      "last_name": "Dale",
      "title": "Sykepleier",
      "skift": 1,
      "Beredskapslag_1": 10,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 25,
      "person_id": 25117720600,
      "first_name": "Wenche",
      "last_name": "Bjørnstad",
      "title": "Catering 1",
      "skift": 1,
      "Beredskapslag_1": 6,
      "Rolle_lag_1": "",
      "Beredskapslag_2": 12,
      "Beredskapslag_3": 3
    },
    {
      "emp_id": 26,
      "person_id": 23066216349,
      "first_name": "Øystein",
      "last_name": "Bråten",
      "title": "Catering 2",
      "skift": 1,
      "Beredskapslag_1": 6,
      "Rolle_lag_1": 5,
      "Beredskapslag_2": 12,
      "Beredskapslag_3": 3
    },
    {
      "emp_id": 27,
      "person_id": 13076610309,
      "first_name": "Ingrid",
      "last_name": "Carlsen",
      "title": "Fagansvalig elektro",
      "skift": 1,
      "Beredskapslag_1": 4,
      "Rolle_lag_1": "",
      "Beredskapslag_2": 12,
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 28,
      "person_id": 27048929155,
      "first_name": "Erik",
      "last_name": "Ali",
      "title": "Stuert",
      "skift": 1,
      "Beredskapslag_1": 12,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 29,
      "person_id": "08099422824",
      "first_name": "Eirik",
      "last_name": "Breivik",
      "title": "Fagansvarlig mekanisk",
      "skift": 1,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": 9,
      "Beredskapslag_2": 6,
      "Beredskapslag_3": 3
    },
    {
      "emp_id": 30,
      "person_id": 22085213052,
      "first_name": "Ida",
      "last_name": "Bye",
      "title": "Elektriker",
      "skift": 1,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 31,
      "person_id": 15018445902,
      "first_name": "Anita",
      "last_name": "Dalen",
      "title": "Prosessoperatør 1",
      "skift": 1,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 32,
      "person_id": "09086631323",
      "first_name": "Gunnar",
      "last_name": "Ahmed",
      "title": "Prosessoperatør 2",
      "skift": 1,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 33,
      "person_id": 18127604874,
      "first_name": "Hilde",
      "last_name": "Aase",
      "title": "Prosessoperatør 3",
      "skift": 1,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 34,
      "person_id": 17037034789,
      "first_name": "Trond",
      "last_name": "Bø",
      "title": "Intrumenttekniker",
      "skift": 1,
      "Beredskapslag_1": 4,
      "Rolle_lag_1": "",
      "Beredskapslag_2": 12,
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 35,
      "person_id": 25089727122,
      "first_name": "Harald",
      "last_name": "Berger",
      "title": "Mekaniker",
      "skift": 1,
      "Beredskapslag_1": 4,
      "Rolle_lag_1": 13,
      "Beredskapslag_2": 12,
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 36,
      "person_id": "09025221580",
      "first_name": "Monica",
      "last_name": "Borge",
      "title": "Plattformsjef",
      "skift": 2,
      "Beredskapslag_1": 1,
      "Rolle_lag_1": 7,
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 37,
      "person_id": "01046425126",
      "first_name": "Espen",
      "last_name": "Borgen",
      "title": "Driftsleder",
      "skift": 2,
      "Beredskapslag_1": 1,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 38,
      "person_id": 14108020289,
      "first_name": "Bjørn",
      "last_name": "Arntsen",
      "title": "Vedlikeholdsleder",
      "skift": 2,
      "Beredskapslag_1": 1,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 39,
      "person_id": 17058648949,
      "first_name": "Arne",
      "last_name": "Andersson",
      "title": "Sikkerhetsleder",
      "skift": 2,
      "Beredskapslag_1": 1,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 40,
      "person_id": 12099519574,
      "first_name": "Daniel",
      "last_name": "Arntzen",
      "title": "Fagansvarlig prosess 1",
      "skift": 2,
      "Beredskapslag_1": 11,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 41,
      "person_id": 13038024455,
      "first_name": "Morten",
      "last_name": "Aamodt",
      "title": "Fagansvarlig prosess 2",
      "skift": 2,
      "Beredskapslag_1": 8,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 42,
      "person_id": 13119023739,
      "first_name": "Marius",
      "last_name": "Børresen",
      "title": "Sykepleier",
      "skift": 2,
      "Beredskapslag_1": 10,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 43,
      "person_id": 20125032797,
      "first_name": "Martin",
      "last_name": "Davidsen",
      "title": "Catering 1",
      "skift": 2,
      "Beredskapslag_1": 6,
      "Rolle_lag_1": "",
      "Beredskapslag_2": 12,
      "Beredskapslag_3": 3
    },
    {
      "emp_id": 44,
      "person_id": "03017319514",
      "first_name": "Nina",
      "last_name": "Berget",
      "title": "Catering 2",
      "skift": 2,
      "Beredskapslag_1": 6,
      "Rolle_lag_1": 5,
      "Beredskapslag_2": 12,
      "Beredskapslag_3": 3
    },
    {
      "emp_id": 45,
      "person_id": 30049339158,
      "first_name": "Per",
      "last_name": "Brevik",
      "title": "Fagansvalig elektro",
      "skift": 2,
      "Beredskapslag_1": 4,
      "Rolle_lag_1": "",
      "Beredskapslag_2": 12,
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 46,
      "person_id": 18057537678,
      "first_name": "Karin",
      "last_name": "Bjelland",
      "title": "Stuert",
      "skift": 2,
      "Beredskapslag_1": 12,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 47,
      "person_id": "03066841676",
      "first_name": "Magnus",
      "last_name": "Bolstad",
      "title": "Fagansvarlig mekanisk",
      "skift": 2,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": 9,
      "Beredskapslag_2": 6,
      "Beredskapslag_3": 3
    },
    {
      "emp_id": 48,
      "person_id": "05119710571",
      "first_name": "Håkon",
      "last_name": "Bergersen",
      "title": "Elektriker",
      "skift": 2,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 49,
      "person_id": 12019505217,
      "first_name": "Elisabeth",
      "last_name": "Bredesen",
      "title": "Prosessoperatør 1",
      "skift": 2,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 50,
      "person_id": 23118106490,
      "first_name": "Tove",
      "last_name": "Bendiksen",
      "title": "Prosessoperatør 2",
      "skift": 2,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 51,
      "person_id": 15109826801,
      "first_name": "Linda",
      "last_name": "Aasheim",
      "title": "Prosessoperatør 3",
      "skift": 2,
      "Beredskapslag_1": 2,
      "Rolle_lag_1": "",
      "Beredskapslag_2": "",
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 52,
      "person_id": 25046527227,
      "first_name": "Odd",
      "last_name": "Bjørnsen",
      "title": "Intrumenttekniker",
      "skift": 2,
      "Beredskapslag_1": 4,
      "Rolle_lag_1": "",
      "Beredskapslag_2": 13,
      "Beredskapslag_3": ""
    },
    {
      "emp_id": 53,
      "person_id": "07018933920",
      "first_name": "Ann",
      "last_name": "Christoffersen",
      "title": "Mekaniker",
      "skift": 2,
      "Beredskapslag_1": 4,
      "Rolle_lag_1": 13,
      "Beredskapslag_2": 13,
      "Beredskapslag_3": ""
    }
  ]