import Status from '../helpers/Status';

export const teamList = [
  {
    id: 0,
    name: "Beredskapsledelse",
    status: Status.OK,
    members: [0],
    requiredCompetence: [0],
    hasTraining: false,
    hasTableTops: true,
  },
  {
    id: 1,
    name: "Kontrollromsoperatører",
    status: Status.WARNING,
    members: [0],
    requiredCompetence: [0, 1],
    hasTraining: false,
    hasTableTops: true,
  },
  {
    id: 2,
    name: "Sykepleier",
    status: Status.OK,
    members: [0],
    requiredCompetence: [0],
    hasTraining: false,
    hasTableTops: false,
  },
  {
    id: 3,
    name: "Helidekklag",
    status: Status.OK,
    members: [0],
    requiredCompetence: [0],
    hasTraining: true,
    hasTableTops: false,
  },
  {
    id: 4,
    name: "Livbåtlag",
    status: Status.OK,
    members: [0],
    requiredCompetence: [0],
    hasTraining: true,
    hasTableTops: false,
  },
  {
    id: 5,
    name: "Skadestedsleder",
    status: Status.OK,
    members: [0],
    requiredCompetence: [0],
    hasTraining: false,
    hasTableTops: false,
  },
  {
    id: 6,
    name: "Søk- og redningslag",
    status: Status.ERROR,
    members: [0, 1, 2, 3, 4],
    requiredCompetence: [0, 1, 2],
    hasTraining: true,
    hasTableTops: false,
  },
  {
    id: 7,
    name: "Førstehjelpslag",
    status: Status.OK,
    members: [0],
    requiredCompetence: [0],
    hasTraining: true,
    hasTableTops: false,
  },
  {
    id: 8,
    name: "MOB-båtlag",
    status: Status.WARNING,
    members: [0],
    requiredCompetence: [0, 1],
    hasTraining: true,
    hasTableTops: false,
  },
];

export const teamById = {};
teamList.forEach(team => teamById[team.id] = team);
